version: "2.4"

services:
  web:
    image: nginxdemos/nginx-hello
    depends_on:
      - modsec
    networks:
      - internal

  modsec:
    build: ./src
    ports:
      - "80:8080"
      - "443:8443"
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./src/html/:/usr/share/nginx/html/

networks:
  internal:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd00:dead:beef::/48
